[package]
name = "cosmere_search_web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = "0.19.1"
serde = { version = "~1.0.147", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3.4", features = ["fs", "set-header", "trace"] }
axum = "0.6.0"
axum-extra = { version = "0.4.0", features = ["form"] }
askama = "0.11.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["std"] }

[profile.dev]
debug = true

[profile.release]
debug = true