[package]
name = "cosmere_search_web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = "0.18.1"
serde = { version = "~1.0.147", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3.4", features = ["fs", "set-header"] }
hyper = "0.14"
axum = { version = "0.5.17", features = ["http2"] }
askama = "0.11.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["std"] }
prometheus-client = "0.18.1"
futures = "0.3"

[profile.dev]
debug = 0

[profile.release]
debug = 0
strip = "symbols"
incremental = false