[package]
name = "cosmere-epub-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epub = "1.2.4"
html2text = "0.4.3"
tantivy = "0.18.1"
serde = "1.0.147"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3.4", features = ["fs", "set-header"] }
axum = { version = "0.5.17", features = ["http2"] }
askama = "0.11.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["std"] }

[profile.dev]
debug = 0

[profile.release]
debug = 0